services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./conf.d/:/etc/nginx/conf.d/
    depends_on:
      - api
    links:
      - api
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync

  api:
    build:
      context: ./libs/php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
