services:
  web:
    image: nginx:latest
    expose:
      - ${WEB_PORT}
    volumes:
      - ../files/./:/var/www/html
      - ../files/conf.d/:/etc/nginx/conf.d/
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-app.rule=Host(${WEB})
      - traefik.http.routers.web-app.entrypoints=websecure
      - traefik.http.routers.web-app.tls.certResolver=letsencrypt
      - traefik.http.services.web-app.loadbalancer.server.port=${WEB_PORT}
    links:
      - api
    depends_on:
      - api
    networks:
      - dokploy-network
    env_file:
      - .env

  api:
    image: php:8.2-fpm
    volumes:
      - ../files/./:/var/www/html
    expose:
      - ${API_PORT}
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-app.rule=Host(${API})
      - traefik.http.routers.api-app.entrypoints=websecure
      - traefik.http.routers.api-app.tls.certResolver=letsencrypt
      - traefik.http.services.api-app.loadbalancer.server.port=${API_PORT}

networks:
  dokploy-network:
    external: true
